### PR TITLE
chore: Update node to 14.18.0 (latest LTS)

### PR DESCRIPTION
**Pull request by akash1810**
## What does this change?

Updates node to the [latest LTS](https://nodejs.org/en/about/releases/).

## Does this change require changes to existing projects or CDK CLI?

No.

## Does this change require changes to the library documentation?

No.

## How to test

CI should continue to pass.

## How can we measure success?

Staying up to date.

## Have we considered potential risks?

n/a

### CODE REVIEW

**Comment by jacobwinch** [comment]
It looks like we are also setting the node version in our workflow files e.g.

https://github.com/guardian/cdk/blob/060d4f73ea2c2fe9d58aeccf32cc2be8fe208fc9/.github/workflows/cd.yaml#L10-L18

Perhaps we should move to https://github.com/guardian/actions-setup-node as part of this change?

**Comment by akash1810** [comment]
> It looks like we are also setting the node version in our workflow files e.g.
> 
> https://github.com/guardian/cdk/blob/060d4f73ea2c2fe9d58aeccf32cc2be8fe208fc9/.github/workflows/cd.yaml#L10-L18
> 
> Perhaps we should move to https://github.com/guardian/actions-setup-node as part of this change?

I should have mentioned this PR builds on top of #828, which makes that move.

**Comment by jacobwinch** [comment]
> I should have mentioned this PR builds on top of #828, which makes that move.

Ah yes, sorry, I see that now!

**Review by jacobwinch — APPROVED** [review]
👍

**Pull request merged**
