### PR TITLE
tweak dependabot's commit messages

### PR DESCRIPTION
**Pull request by akash1810**
## What does this change?

Prefix commits with "chore(deps): " to indicate the type of change. This is to help the robots understand history and automate the creation of release notes and new release version numbers.

See:
- https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines
- http://karma-runner.github.io/6.0/dev/git-commit-msg.html
- https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#commit-message
- #225 

## Does this change require changes to existing projects or CDK CLI?

No.

## How to test

n/a

## How can we measure success?

We're closer to automating releases - structured commits help robots parse history.

## Have we considered potential risks?

n/a

### CODE REVIEW

**Review by jacobwinch — APPROVED** [review]
I'm not sure if this is still necessary if we've decided to use PR-based linting: https://github.com/guardian/cdk/pull/225?

I'm happy to merge this if it's still needed / useful for other reasons though!

**Comment by akash1810** [comment]
> I'm not sure if this is still necessary if we've decided to use PR-based linting: #225?

As I understand it, dependabot uses the commit message as the PR title. I've assumed this from the [master-to-main repo](https://github.com/guardian/master-to-main/pulls?q=is%3Apr+is%3Aopen+label%3Adependencies).

**Comment by jacobwinch** [comment]
> As I understand it, dependabot uses the commit message as the PR title.

Ah yes, that makes sense. Thanks for explaining!

**Comment by akash1810** [comment]
https://github.com/guardian/cdk/pull/228 the theory is correct! 🎉

**Pull request merged**
