### PR TITLE
feat: Simplify props for `GuLambdaFunction`

### PR DESCRIPTION
**Pull request by akash1810**
## What does this change?

Simplifies the props needed to create a `GuLambdaFunction` by removing the bucket key in favour of using the `GuDistributionBucketParameter` singleton.

This brings `GuLambdaFunction` in line with our EC2 constructs and patterns.

`GuDistributionBucketParameter` adds an SSM parameter to a stack with a default path of `/account/services/artifact.bucket`.

BREAKING CHANGE: Shape change to the props for `GuLambdaFunction`

The `code.bucket` field has been removed.

## Does this change require changes to existing projects or CDK CLI?

Yes. They'll need to update, the diff shouldn't be too difficult though as it's just the removal of a property.

## How to test

CI should continue to pass.

## How can we measure success?

Providing a simpler API that is consistent between EC2 and Lambda constructs.

## Have we considered potential risks?

n/a

### CODE REVIEW

**Review by jacobwinch — APPROVED** [review]
Good idea 👍 

It would be good to document this convention too; feel free to do that later / in a separate PR though if you are trying to make progress with other changes which are dependent on this.

**Comment by akash1810** [comment]
> It would be good to document this convention too

Yes! Not sure where though. Any suggestions?

**Comment by jacobwinch** [comment]
> Yes! Not sure where though. Any suggestions?

Maybe it should go with `GuFunctionProps`? The lambda-based pattern docs [typically point users in this direction](https://github.com/guardian/cdk/blob/2b3296f18a690b523be02ba40a076f92d40ecc83/src/patterns/kinesis-lambda.ts#L51), to avoid repeating the same docs in lots of places.

**Comment by akash1810** [comment]
A thought: I think we'd want to enforce the path of the lambda distributable in the bucket, similar to we do for EC2. #259 tightened the `GuGetDistributablePolicy` to allow `s3:GetObject` on the `stack/stage/app/*` path.

**Comment by akash1810** [comment]
Another thought, we might benefit from reusing [`GuUserDataS3DistributableProps`](https://github.com/guardian/cdk/blob/e79b15ce34717b1b0e3a17bead74ae34c24f5662/src/constructs/autoscaling/user-data.ts#L13) in `GuFunctionProps`? I think that would be +1 to having a top level `types` directory too.

**Comment by akash1810** [comment]
> > Yes! Not sure where though. Any suggestions?
> 
> Maybe it should go with `GuFunctionProps`? The lambda-based pattern docs [typically point users in this direction](https://github.com/guardian/cdk/blob/2b3296f18a690b523be02ba40a076f92d40ecc83/src/patterns/kinesis-lambda.ts#L51), to avoid repeating the same docs in lots of places.

Added now.

**Pull request merged**
