### PR TITLE
chore(deps)!: Update aws-cdk libraries to 1.110.1

### PR DESCRIPTION
**Pull request by jacobwinch**
BREAKING CHANGE: Update aws-cdk libraries to 1.110.1

### CODE REVIEW

**Review by akash1810 — COMMENTED** [review]
There's a bug in the `update-aws-cdk` script as I think `integration-test/package-lock.json` should have changed too (since #570)? Probably [this line](https://github.com/guardian/cdk/blob/a5e1337b2b7f1d9ec1b5e1eb4e5b0adf0db1f393/script/update-aws-cdk#L54).

It also looks like this is a v2 lockfile, which comes from npmv7. Is this desired? See #340.

**Comment by jacobwinch** [comment]
Thanks @akash1810 - I had trusted the script without checking. Will close this and have a proper look!

**Comment by akash1810** [comment]
We might be able to move to NPMv7 as @JamieB-gu recently pointed out that the npm version is [tied](https://nodejs.org/en/download/releases/) to the node version ([demo](#608)).

**Comment by jacobwinch** [comment]
> It also looks like this is a v2 lockfile, which comes from npmv7. Is this desired? See #340.

This part definitely wasn't desired, in fact I don't understand how it happened yet!

**Comment by JamieB-gu** [comment]
> in fact I don't understand how it happened yet!

Which version of `npm` did you use to make this change? If you were on v7 could that have caused the migration?

**Comment by jacobwinch** [comment]
> Which version of `npm` did you use to make this change? If you were on v7 could that have caused the migration?

See: https://github.com/guardian/cdk/pull/642#discussion_r660404644. `6.14.8` _and_ (accidentally) 7.x!

**Pull request closed without merging**
